theme = "gruvbox"

[editor]
bufferline = "multiple"
line-number = "relative"
cursorline = true
color-modes = true
true-color = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"
