[[language]]
name = "python"
language-servers = [
  { name = "pyright" },
  { name = "ruff" },
  { name = "mypy "} 
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]
